export const GET_INTERVIEW_JD = "GET_INTERVIEW_JD"
export const GET_INTERVIEW_APPLICATION_REQUEST = "GET_INTERVIEW_APPLICATION_REQUEST"
export const GET_INTERVIEW_APPLICATION_REQUEST_SUCCESS = "GET_INTERVIEW_APPLICATION_REQUEST_SUCCESS"
export const GET_INTERVIEW_APPLICATION_REQUEST_FAILURE = "GET_INTERVIEW_APPLICATION_REQUEST_FAILURE"

export const GET_CANDIDATE_EVALUATION_REQUEST = "GET_CANDIDATE_EVALUATION_REQUEST"
export const GET_CANDIDATE_EVALUATION_REQUEST_SUCCESS = "GET_CANDIDATE_EVALUATION_REQUEST_SUCCESS"
export const GET_CANDIDATE_EVALUATION_REQUEST_FAILURE = "GET_CANDIDATE_EVALUATION_REQUEST_FAILURE"


export const getEvaluationOfCandidate = (id,candidates) => {
    return {
       type: GET_CANDIDATE_EVALUATION_REQUEST,
       payload:{id,data:candidates}
    }
}

